DEBUG 2018-07-06 15:47:04,089: 	 Executing command: 'submit'
DEBUG 2018-07-06 15:47:04,089: 	 Found CRAB cache file /home/cms-opendata/.crab3
DEBUG 2018-07-06 15:47:04,101: 	 Checking credentials
DEBUG 2018-07-06 15:47:04,101: 	 Found proxy file /tmp/x509up_u1000
DEBUG 2018-07-06 15:47:04,101: 	 Getting proxy life time left
DEBUG 2018-07-06 15:47:04,815: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1000 -timeleft
 output : 43163

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:05,438: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1000 -actimeleft
 output : 
 error: No VOMS attributes found!

 retcode : 1
DEBUG 2018-07-06 15:47:05,438: 	 Proxy valid for 00:00:00 hours
DEBUG 2018-07-06 15:47:05,438: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2018-07-06 15:47:11,927: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2018-07-06 15:47:12,551: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1000 -timeleft
 output : 86398

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:13,182: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1000 -actimeleft
 output : 86399

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:13,905: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u1000 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:13,906: 	 Proxy created.
INFO 2018-07-06 15:47:13,906: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2018-07-06 15:47:13,907: 	 Loading CRAB configuration file.
DEBUG 2018-07-06 15:47:13,912: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2018-07-06 15:47:14,067: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fnavarro/CN=819205/CN=Felipe Mateo Navarro Cordero

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:14,068: 	 Checking credentials
DEBUG 2018-07-06 15:47:14,069: 	 Found proxy file /tmp/x509up_u1000
DEBUG 2018-07-06 15:47:14,069: 	 Getting proxy life time left
DEBUG 2018-07-06 15:47:14,794: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1000 -timeleft
 output : 86396

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:15,415: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u1000 -actimeleft
 output : 86397

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:15,415: 	 Proxy valid for 23:59:56 hours
DEBUG 2018-07-06 15:47:16,127: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u1000 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:16,418: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch
DEBUG 2018-07-06 15:47:16,551: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fnavarro/CN=819205/CN=Felipe Mateo Navarro Cordero

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:16,552: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2018-07-06 15:47:16,553: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fnavarro/CN=819205/CN=Felipe Mateo Navarro Cordero_cmsweb.cern.ch for credential name
DEBUG 2018-07-06 15:47:16,667: 	 Executing : 
 command : myproxy-info -l f24bebe16bd5231e8d0ce6d2b1fa01f9e633539e -s myproxy.cern.ch
 output : 
 error: myproxy-info: error while loading shared libraries: libsasl2.so.2: cannot open shared object file: No such file or directory

 retcode : 127
DEBUG 2018-07-06 15:47:16,667: 	 Myproxy is valid: -1
DEBUG 2018-07-06 15:47:16,773: 	 Executing : 
 command : openssl x509 -noout -in ~/.globus/usercert.pem -dates
 output : notBefore=Aug  9 19:21:14 2017 GMT
notAfter=Sep 13 19:21:14 2018 GMT

 error: 
 retcode : 0
DEBUG 2018-07-06 15:47:16,789: 	 Delegating a myproxy for 720:00 hours
DEBUG 2018-07-06 15:47:16,789: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fnavarro/CN=819205/CN=Felipe Mateo Navarro Cordero_cmsweb.cern.ch for credential name
DEBUG 2018-07-06 15:47:16,898: 	 Executing : 
 command : export GT_PROXY_MODE=rfc ; myproxy-init -d -n -s myproxy.cern.ch -x -R '/DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch' -x -Z '/DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119|0108|0105|0109).cern.ch' -l 'f24bebe16bd5231e8d0ce6d2b1fa01f9e633539e' -t 168:00 -c 720:00
 output : 
 error: myproxy-init: error while loading shared libraries: libsasl2.so.2: cannot open shared object file: No such file or directory

 retcode : 127
DEBUG 2018-07-06 15:47:16,898: 	 Calculating hash of /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fnavarro/CN=819205/CN=Felipe Mateo Navarro Cordero_cmsweb.cern.ch for credential name
DEBUG 2018-07-06 15:47:17,004: 	 Executing : 
 command : myproxy-info -l f24bebe16bd5231e8d0ce6d2b1fa01f9e633539e -s myproxy.cern.ch
 output : 
 error: myproxy-info: error while loading shared libraries: libsasl2.so.2: cannot open shared object file: No such file or directory

 retcode : 127
ERROR 2018-07-06 15:47:17,005: 	 Problems delegating My-proxy. It seems your proxy has not been delegated to myproxy. Please check the logfile for the exact error (it might simply you typed a wrong password)
ERROR 2018-07-06 15:47:17,005: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 342, in __init__
    self.handleProxy(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 422, in handleProxy
    self.proxy.createNewMyProxy(timeleftthreshold = 60 * 60 * 24 * RENEW_MYPROXY_THRESHOLD, nokey = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 348, in createNewMyProxy
    raise ProxyCreationException("Problems delegating My-proxy. %s" % msg)
ProxyCreationException: Problems delegating My-proxy. It seems your proxy has not been delegated to myproxy. Please check the logfile for the exact error (it might simply you typed a wrong password)
